"""Os nomes do bestiário em português, com a grafia da edição brasileira da 5e
sempre que ela existe. O importador aceita o nome em inglês também, então quem
monta a sala pode escrever qualquer um dos dois.
"""

_DRAGOES = {
    "Black": "Negro", "Blue": "Azul", "Brass": "de Latão", "Bronze": "de Bronze",
    "Copper": "de Cobre", "Gold": "Dourado", "Green": "Verde", "Red": "Vermelho",
    "Silver": "Prateado", "White": "Branco",
}

CRIATURAS = {
    "Aarakocra": "Aarakocra",
    "Aboleth": "Aboleth",
    "Abominable Yeti": "Yeti Abominável",
    "Acolyte": "Acólito",
    "Adult Blue Dracolich": "Dracolich Azul Adulto",
    "Air Elemental": "Elemental do Ar",
    "Allosaurus": "Alossauro",
    "Androsphinx": "Androesfinge",
    "Animated Armor": "Armadura Animada",
    "Ankheg": "Ankheg",
    "Ankylosaurus": "Anquilossauro",
    "Ape": "Macaco",
    "Arcanaloth": "Arcanaloth",
    "Archmage": "Arquimago",
    "Assassin": "Assassino",
    "Awakened Shrub": "Arbusto Desperto",
    "Awakened Tree": "Árvore Desperta",
    "Axe Beak": "Bico de Machado",
    "Azer": "Azer",
    "Baboon": "Babuíno",
    "Badger": "Texugo",
    "Balor": "Balor",
    "Bandit": "Bandido",
    "Bandit Captain": "Capitão Bandido",
    "Banshee": "Banshee",
    "Barbed Devil": "Diabo Farpado",
    "Barlgura": "Barlgura",
    "Basilisk": "Basilisco",
    "Bat": "Morcego",
    "Bearded Devil": "Diabo Barbado",
    "Behir": "Behir",
    "Beholder": "Observador",
    "Beholder Zombie": "Observador Zumbi",
    "Berserker": "Berserker",
    "Black Bear": "Urso Negro",
    "Black Pudding": "Pudim Negro",
    "Blink Dog": "Cão Intermitente",
    "Blood Hawk": "Falcão Sangrento",
    "Blue Slaad": "Slaad Azul",
    "Boar": "Javali",
    "Bone Devil": "Diabo Ósseo",
    "Bone Naga (Guardian)": "Naga Óssea (Guardiã)",
    "Bone Naga (Spirit)": "Naga Óssea (Espiritual)",
    "Brown Bear": "Urso Pardo",
    "Bugbear": "Bugbear",
    "Bugbear Chief": "Chefe Bugbear",
    "Bulette": "Bulette",
    "Bullywug": "Bullywug",
    "Cambion": "Cambion",
    "Camel": "Camelo",
    "Carrion Crawler": "Rastejador da Carniça",
    "Cat": "Gato",
    "Cave Bear": "Urso das Cavernas",
    "Centaur": "Centauro",
    "Chain Devil": "Diabo das Correntes",
    "Chasme": "Chasme",
    "Chimera": "Quimera",
    "Chuul": "Chuul",
    "Clay Golem": "Golem de Barro",
    "Cloaker": "Espreitador Manto",
    "Cloud Giant": "Gigante das Nuvens",
    "Cockatrice": "Cocatriz",
    "Commoner": "Plebeu",
    "Constrictor Snake": "Cobra Constritora",
    "Couatl": "Couatl",
    "Crab": "Caranguejo",
    "Crawling Claw": "Garra Rastejante",
    "Crocodile": "Crocodilo",
    "Cult Fanatic": "Fanático do Culto",
    "Cultist": "Cultista",
    "Cyclops": "Ciclope",
    "Dao": "Dao",
    "Darkmantle": "Manto Negro",
    "Death Dog": "Cão da Morte",
    "Death Knight": "Cavaleiro da Morte",
    "Death Slaad": "Slaad da Morte",
    "Death Tyrant": "Tirano da Morte",
    "Deep Gnome (Svirfneblin)": "Gnomo das Profundezas (Svirfneblin)",
    "Deer": "Cervo",
    "Deva": "Deva",
    "Dire Wolf": "Lobo Atroz",
    "Displacer Beast": "Besta Deslocadora",
    "Djinni": "Djinni",
    "Doppelganger": "Doppelganger",
    "Draft Horse": "Cavalo de Tração",
    "Dragon Turtle": "Tartaruga-Dragão",
    "Dretch": "Dretch",
    "Drider": "Drider",
    "Drow": "Drow",
    "Drow Elite Warrior": "Guerreiro de Elite Drow",
    "Drow Mage": "Mago Drow",
    "Drow Priestess of Lolth": "Sacerdotisa Drow de Lolth",
    "Druid": "Druida",
    "Dryad": "Dríade",
    "Duergar": "Duergar",
    "Duodrone": "Duodrone",
    "Dust Mephit": "Mefite de Poeira",
    "Eagle": "Águia",
    "Earth Elemental": "Elemental da Terra",
    "Efreeti": "Efreeti",
    "Elephant": "Elefante",
    "Elk": "Alce",
    "Empyrean": "Empíreo",
    "Erinyes": "Erínia",
    "Ettercap": "Ettercap",
    "Ettin": "Ettin",
    "Faerie Dragon (Blue)": "Dragão Feérico (Azul)",
    "Faerie Dragon (Green)": "Dragão Feérico (Verde)",
    "Faerie Dragon (Indigo)": "Dragão Feérico (Anil)",
    "Faerie Dragon (Orange)": "Dragão Feérico (Laranja)",
    "Faerie Dragon (Red)": "Dragão Feérico (Vermelho)",
    "Faerie Dragon (Violet)": "Dragão Feérico (Violeta)",
    "Faerie Dragon (Yellow)": "Dragão Feérico (Amarelo)",
    "Fire Elemental": "Elemental do Fogo",
    "Fire Giant": "Gigante do Fogo",
    "Fire Snake": "Serpente de Fogo",
    "Flameskull": "Crânio Flamejante",
    "Flesh Golem": "Golem de Carne",
    "Flumph": "Flumph",
    "Flying Snake": "Cobra Voadora",
    "Flying Sword": "Espada Voadora",
    "Fomorian": "Fomoriano",
    "Frost Giant": "Gigante do Gelo",
    "Galeb Duhr": "Galeb Duhr",
    "Gargoyle": "Gárgula",
    "Gas Spore": "Esporo Gasoso",
    "Gelatinous Cube": "Cubo Gelatinoso",
    "Ghast": "Lívido",
    "Ghost": "Fantasma",
    "Ghoul": "Carniçal",
    "Giant Ape": "Macaco Gigante",
    "Giant Badger": "Texugo Gigante",
    "Giant Bat": "Morcego Gigante",
    "Giant Boar": "Javali Gigante",
    "Giant Centipede": "Centopeia Gigante",
    "Giant Constrictor Snake": "Cobra Constritora Gigante",
    "Giant Crab": "Caranguejo Gigante",
    "Giant Crocodile": "Crocodilo Gigante",
    "Giant Eagle": "Águia Gigante",
    "Giant Elk": "Alce Gigante",
    "Giant Fire Beetle": "Besouro de Fogo Gigante",
    "Giant Frog": "Sapo Gigante",
    "Giant Goat": "Bode Gigante",
    "Giant Hyena": "Hiena Gigante",
    "Giant Lizard": "Lagarto Gigante",
    "Giant Octopus": "Polvo Gigante",
    "Giant Owl": "Coruja Gigante",
    "Giant Poisonous Snake": "Cobra Venenosa Gigante",
    "Giant Rat": "Rato Gigante",
    "Giant Scorpion": "Escorpião Gigante",
    "Giant Sea Horse": "Cavalo-Marinho Gigante",
    "Giant Shark": "Tubarão Gigante",
    "Giant Spider": "Aranha Gigante",
    "Giant Toad": "Sapo-Boi Gigante",
    "Giant Vulture": "Abutre Gigante",
    "Giant Wasp": "Vespa Gigante",
    "Giant Weasel": "Doninha Gigante",
    "Giant Wolf Spider": "Aranha-Lobo Gigante",
    "Gibbering Mouther": "Boca Tagarela",
    "Githyanki Knight": "Cavaleiro Githyanki",
    "Githyanki Warrior": "Guerreiro Githyanki",
    "Githzerai Monk": "Monge Githzerai",
    "Githzerai Zerth": "Zerth Githzerai",
    "Glabrezu": "Glabrezu",
    "Gladiator": "Gladiador",
    "Gnoll": "Gnoll",
    "Gnoll Fang of Yeenoghu": "Presa de Yeenoghu Gnoll",
    "Gnoll Pack Lord": "Líder de Matilha Gnoll",
    "Goat": "Bode",
    "Goblin": "Goblin",
    "Goblin Boss": "Chefe Goblin",
    "Gorgon": "Górgona",
    "Goristro": "Goristro",
    "Gray Ooze": "Gosma Cinzenta",
    "Gray Slaad": "Slaad Cinzento",
    "Green Hag": "Bruxa Verde",
    "Green Slaad": "Slaad Verde",
    "Grell": "Grell",
    "Grick": "Grick",
    "Grick Alpha": "Grick Alfa",
    "Griffon": "Grifo",
    "Grimlock": "Grimlock",
    "Guard": "Guarda",
    "Guardian Naga": "Naga Guardiã",
    "Gynosphinx": "Ginoesfinge",
    "Half-Ogre (Ogrillon)": "Meio-Ogro (Ogrillon)",
    "Half-Red Dragon Veteran": "Veterano Meio-Dragão Vermelho",
    "Harpy": "Harpia",
    "Hawk": "Falcão",
    "Hell Hound": "Cão Infernal",
    "Helmed Horror": "Horror de Elmo",
    "Hezrou": "Hezrou",
    "Hill Giant": "Gigante da Colina",
    "Hippogriff": "Hipogrifo",
    "Hobgoblin": "Hobgoblin",
    "Hobgoblin Captain": "Capitão Hobgoblin",
    "Hobgoblin Warlord": "Senhor da Guerra Hobgoblin",
    "Homunculus": "Homúnculo",
    "Hook Horror": "Horror de Gancho",
    "Horned Devil": "Diabo Chifrudo",
    "Hunter Shark": "Tubarão Caçador",
    "Hydra": "Hidra",
    "Hyena": "Hiena",
    "Ice Devil": "Diabo do Gelo",
    "Ice Mephit": "Mefite de Gelo",
    "Imp": "Diabrete",
    "Incubus": "Íncubo",
    "Intellect Devourer": "Devorador de Intelecto",
    "Invisible Stalker": "Perseguidor Invisível",
    "Iron Golem": "Golem de Ferro",
    "Jackal": "Chacal",
    "Jackalwere": "Chacalobisomem",
    "Kenku": "Kenku",
    "Killer Whale": "Orca",
    "Knight": "Cavaleiro",
    "Kobold": "Kobold",
    "Kraken": "Kraken",
    "Kuo-toa": "Kuo-toa",
    "Kuo-toa Archpriest": "Arquissacerdote Kuo-toa",
    "Kuo-toa Monitor": "Monitor Kuo-toa",
    "Kuo-toa Whip": "Chicote Kuo-toa",
    "Lamia": "Lâmia",
    "Lemure": "Lêmure",
    "Lich": "Lich",
    "Lion": "Leão",
    "Lizard": "Lagarto",
    "Lizard King": "Rei Lagarto",
    "Lizard Queen": "Rainha Lagarto",
    "Lizardfolk": "Homem-Lagarto",
    "Lizardfolk Shaman": "Xamã Homem-Lagarto",
    "Mage": "Mago",
    "Magma Mephit": "Mefite de Magma",
    "Magmin": "Magmin",
    "Mammoth": "Mamute",
    "Manes": "Manes",
    "Manticore": "Mantícora",
    "Marid": "Marid",
    "Marilith": "Marilith",
    "Mastiff": "Mastim",
    "Medusa": "Medusa",
    "Merfolk": "Tritão",
    "Merrow": "Merrow",
    "Mezzoloth": "Mezzoloth",
    "Mimic": "Mímico",
    "Mind Flayer": "Devorador de Mentes",
    "Mind Flayer Arcanist": "Devorador de Mentes Arcanista",
    "Minotaur": "Minotauro",
    "Minotaur Skeleton": "Esqueleto de Minotauro",
    "Monodrone": "Monodrone",
    "Mud Mephit": "Mefite de Lama",
    "Mule": "Mula",
    "Mummy": "Múmia",
    "Mummy Lord": "Senhor Múmia",
    "Myconid Adult": "Miconídeo Adulto",
    "Myconid Sovereign": "Miconídeo Soberano",
    "Myconid Sprout": "Miconídeo Broto",
    "Nalfeshnee": "Nalfeshnee",
    "Needle Blight": "Praga de Agulhas",
    "Night Hag": "Bruxa da Noite",
    "Nightmare": "Pesadelo",
    "Noble": "Nobre",
    "Nothic": "Nothic",
    "Nycaloth": "Nycaloth",
    "Ochre Jelly": "Geleia Ocre",
    "Octopus": "Polvo",
    "Ogre": "Ogro",
    "Ogre Zombie": "Ogro Zumbi",
    "Oni": "Oni",
    "Orc": "Orc",
    "Orc Eye of Gruumsh": "Olho de Gruumsh Orc",
    "Orc War Chief": "Chefe de Guerra Orc",
    "Orog": "Orog",
    "Otyugh": "Otyugh",
    "Owl": "Coruja",
    "Owlbear": "Urso-Coruja",
    "Panther": "Pantera",
    "Pegasus": "Pégaso",
    "Pentadrone": "Pentadrone",
    "Peryton": "Periton",
    "Phase Spider": "Aranha de Fase",
    "Piercer": "Perfurador",
    "Pit Fiend": "Diabo das Profundezas",
    "Planetar": "Planetar",
    "Plesiosaurus": "Plesiossauro",
    "Poisonous Snake": "Cobra Venenosa",
    "Polar Bear": "Urso Polar",
    "Poltergeist": "Poltergeist",
    "Pony": "Pônei",
    "Priest": "Sacerdote",
    "Pseudodragon": "Pseudodragão",
    "Pteranodon": "Pteranodonte",
    "Purple Worm": "Verme Púrpura",
    "Quadrone": "Quadrone",
    "Quaggoth": "Quaggoth",
    "Quaggoth Spore Servant": "Quaggoth Servo dos Esporos",
    "Quaggoth Thonot": "Quaggoth Thonot",
    "Quasit": "Quasit",
    "Quipper": "Piranha",
    "Rakshasa": "Rakshasa",
    "Rat": "Rato",
    "Raven": "Corvo",
    "Red Slaad": "Slaad Vermelho",
    "Reef Shark": "Tubarão de Recife",
    "Remorhaz": "Remorhaz",
    "Revenant": "Aparição Vingativa",
    "Rhinoceros": "Rinoceronte",
    "Riding Horse": "Cavalo de Montaria",
    "Roc": "Roca",
    "Roper": "Laçador",
    "Rust Monster": "Monstro da Ferrugem",
    "Saber-Toothed Tiger": "Tigre Dentes-de-Sabre",
    "Sahuagin": "Sahuagin",
    "Sahuagin Baron": "Barão Sahuagin",
    "Sahuagin Priestess": "Sacerdotisa Sahuagin",
    "Salamander": "Salamandra",
    "Satyr": "Sátiro",
    "Scarecrow": "Espantalho",
    "Scorpion": "Escorpião",
    "Scout": "Batedor",
    "Sea Hag": "Bruxa do Mar",
    "Shadow": "Sombra",
    "Shadow Demon": "Demônio das Sombras",
    "Shambling Mound": "Monte Errante",
    "Shield Guardian": "Guardião Protetor",
    "Skeleton": "Esqueleto",
    "Slaad Tadpole": "Girino Slaad",
    "Smoke Mephit": "Mefite de Fumaça",
    "Solar": "Solar",
    "Spectator": "Espectador",
    "Specter": "Espectro",
    "Spider": "Aranha",
    "Spined Devil": "Diabo Espinhoso",
    "Spirit Naga": "Naga Espiritual",
    "Sprite": "Sprite",
    "Spy": "Espião",
    "Steam Mephit": "Mefite de Vapor",
    "Stirge": "Stirge",
    "Stone Giant": "Gigante de Pedra",
    "Stone Golem": "Golem de Pedra",
    "Storm Giant": "Gigante da Tempestade",
    "Succubus": "Súcubo",
    "Swarm of Bats": "Enxame de Morcegos",
    "Swarm of Beetles": "Enxame de Besouros",
    "Swarm of Centipedes": "Enxame de Centopeias",
    "Swarm of Insects": "Enxame de Insetos",
    "Swarm of Poisonous Snakes": "Enxame de Cobras Venenosas",
    "Swarm of Quippers": "Enxame de Piranhas",
    "Swarm of Rats": "Enxame de Ratos",
    "Swarm of Ravens": "Enxame de Corvos",
    "Swarm of Spiders": "Enxame de Aranhas",
    "Swarm of Wasps": "Enxame de Vespas",
    "Tarrasque": "Tarrasque",
    "Thri-kreen": "Thri-kreen",
    "Thug": "Brutamontes",
    "Tiger": "Tigre",
    "Treant": "Ente",
    "Tribal Warrior": "Guerreiro Tribal",
    "Triceratops": "Tricerátops",
    "Tridrone": "Tridrone",
    "Troglodyte": "Troglodita",
    "Troll": "Troll",
    "Twig Blight": "Praga de Galhos",
    "Tyrannosaurus Rex": "Tiranossauro Rex",
    "Ultroloth": "Ultroloth",
    "Umber Hulk": "Colosso Umbral",
    "Unicorn": "Unicórnio",
    "Vampire": "Vampiro",
    "Vampire Spawn": "Cria Vampírica",
    "Vampire Spellcaster": "Vampiro Conjurador",
    "Vampire Warrior": "Vampiro Guerreiro",
    "Veteran": "Veterano",
    "Vine Blight": "Praga de Vinhas",
    "Violet Fungus": "Fungo Violeta",
    "Vrock": "Vrock",
    "Vulture": "Abutre",
    "Warhorse": "Cavalo de Guerra",
    "Warhorse Skeleton": "Esqueleto de Cavalo de Guerra",
    "Water Elemental": "Elemental da Água",
    "Water Weird": "Estranho da Água",
    "Weasel": "Doninha",
    "Werebear": "Urso-Lobisomem",
    "Wereboar": "Javali-Lobisomem",
    "Wererat": "Rato-Lobisomem",
    "Weretiger": "Tigre-Lobisomem",
    "Werewolf": "Lobisomem",
    "Wight": "Aparição",
    "Will-o'-Wisp": "Fogo-Fátuo",
    "Winged Kobold": "Kobold Alado",
    "Winter Wolf": "Lobo do Inverno",
    "Wolf": "Lobo",
    "Worg": "Worg",
    "Wraith": "Espectro Sombrio",
    "Wyvern": "Serpe",
    "Xorn": "Xorn",
    "Yeti": "Yeti",
    "Yochlol": "Yochlol",
    "Young Red Shadow Dragon": "Dragão Vermelho Sombrio Jovem",
    "Young Remorhaz": "Remorhaz Jovem",
    "Yuan-ti Abomination": "Abominação Yuan-ti",
    "Yuan-ti Malison (Type 1)": "Maldito Yuan-ti (Tipo 1)",
    "Yuan-ti Malison (Type 2)": "Maldito Yuan-ti (Tipo 2)",
    "Yuan-ti Malison (Type 3)": "Maldito Yuan-ti (Tipo 3)",
    "Yuan-ti Pureblood": "Sangue-Puro Yuan-ti",
    "Zombie": "Zumbi",
}

# Os dragões cromáticos e metálicos seguem um molde: idade + cor.
for _cor_en, _cor_pt in _DRAGOES.items():
    CRIATURAS[f"{_cor_en} Dragon Wyrmling"] = f"Filhote de Dragão {_cor_pt}"
    for _idade_en, _idade_pt in (("Young", "Jovem"), ("Adult", "Adulto"), ("Ancient", "Ancião")):
        CRIATURAS[f"{_idade_en} {_cor_en} Dragon"] = f"Dragão {_cor_pt} {_idade_pt}"

ACOES = {
    "Acid Breath": "Sopro Ácido",
    "Acid Spray": "Borrifo Ácido",
    "Arm": "Braço",
    "Battleaxe": "Machado de Batalha",
    "Beak": "Bico",
    "Beaks": "Bicos",
    "Beard": "Barba",
    "Bite": "Mordida",
    "Bites": "Mordidas",
    "Blood Drain": "Drenar Sangue",
    "Breath Weapons": "Sopro",
    "Chain": "Corrente",
    "Chilling Gaze": "Olhar Gélido",
    "Claw": "Garra",
    "Claws": "Garras",
    "Club": "Clava",
    "Cold Breath": "Sopro Gélido",
    "Constrict": "Constrição",
    "Corrupting Touch": "Toque Corruptor",
    "Crush": "Esmagar",
    "Dagger": "Adaga",
    "Devour Intellect": "Devorar Intelecto",
    "Draining Kiss": "Beijo Drenante",
    "Dreadful Glare": "Olhar Aterrador",
    "Drop": "Queda",
    "Dropped Rock": "Pedra Largada",
    "Engulf": "Engolfar",
    "Evil Eye": "Mau-Olhado",
    "Eye Ray": "Raio Ocular",
    "Eye Rays": "Raios Oculares",
    "Fire Breath": "Sopro de Fogo",
    "Fire Ray": "Raio de Fogo",
    "Fist": "Punho",
    "Fists": "Punhos",
    "Forceful Slam": "Pancada Poderosa",
    "Fork": "Forcado",
    "Frost Breath": "Sopro Congelante",
    "Glaive": "Glaive",
    "Gore": "Chifrada",
    "Greataxe": "Machado Grande",
    "Greatclub": "Clava Grande",
    "Greatsword": "Espada Grande",
    "Hallucination Spores": "Esporos Alucinógenos",
    "Hand Crossbow": "Besta de Mão",
    "Hellfire Orb": "Orbe de Fogo Infernal",
    "Hoof": "Casco",
    "Hook": "Gancho",
    "Hooves": "Cascos",
    "Horn": "Chifre",
    "Horns": "Chifres",
    "Hypnotic Gaze": "Olhar Hipnótico",
    "Javelin": "Azagaia",
    "Life Drain": "Drenar Vida",
    "Light Crossbow": "Besta Leve",
    "Lightning Breath": "Sopro de Relâmpago",
    "Lightning Storm": "Tempestade de Raios",
    "Lightning Strike": "Descarga Elétrica",
    "Longbow": "Arco Longo",
    "Longsword": "Espada Longa",
    "Luring Song": "Canção Sedutora",
    "Mace": "Maça",
    "Mandibles": "Mandíbulas",
    "Maul": "Malho",
    "Mind Blast": "Rajada Mental",
    "Mist Form": "Forma de Névoa",
    "Morningstar": "Maça Estrela",
    "Needles": "Agulhas",
    "Pacifying Spores": "Esporos Pacificadores",
    "Paralysis Gas": "Gás Paralisante",
    "Paralyzing Touch": "Toque Paralisante",
    "Parry": "Aparar",
    "Petrifying Breath": "Sopro Petrificante",
    "Pike": "Pique",
    "Pincer": "Pinça",
    "Pincer Staff": "Cajado de Pinça",
    "Poison Breath": "Sopro Venenoso",
    "Possession": "Possessão",
    "Proboscis": "Probóscide",
    "Pseudopod": "Pseudópode",
    "Quarterstaff": "Bordão",
    "Rake": "Rasgo",
    "Ram": "Investida",
    "Rapier": "Rapieira",
    "Redirect Attack": "Redirecionar Ataque",
    "Roar": "Rugido",
    "Rock Catching": "Apanhar Rochas",
    "Rotting Fist": "Punho Putrefato",
    "Rotting Gaze": "Olhar Putrefato",
    "Rotting Touch": "Toque Putrefato",
    "Scepter": "Cetro",
    "Scimitar": "Cimitarra",
    "Scourge": "Açoite",
    "Shadow Breath": "Sopro Sombrio",
    "Shield": "Escudo",
    "Shock": "Choque",
    "Shortbow": "Arco Curto",
    "Shortsword": "Espada Curta",
    "Silver Greatsword": "Espada Grande de Prata",
    "Slam": "Pancada",
    "Sleep Gaze": "Olhar Sonífero",
    "Snake Hair": "Cabelo de Serpentes",
    "Spear": "Lança",
    "Spell Reflection": "Reflexão de Magia",
    "Spiked Bone Club": "Clava de Osso Cravejada",
    "Spit Poison": "Cuspir Veneno",
    "Split": "Dividir",
    "Spores": "Esporos",
    "Staff": "Cajado",
    "Steam Breath": "Sopro de Vapor",
    "Sticky Shield": "Escudo Grudento",
    "Sting": "Ferroada",
    "Stinger": "Ferrão",
    "Strength Drain": "Drenar Força",
    "Stunning Screech": "Guincho Atordoante",
    "Tail": "Cauda",
    "Talons": "Talões",
    "Tendrils": "Gavinhas",
    "Tentacle": "Tentáculo",
    "Tentacle Slam": "Pancada de Tentáculo",
    "Tentacles": "Tentáculos",
    "Terrifying Glare": "Olhar Aterrorizante",
    "Touch": "Toque",
    "Trident": "Tridente",
    "Tusk": "Presa",
    "Unarmed Strike": "Golpe Desarmado",
    "Unnerving Mask": "Máscara Perturbadora",
    "Vengeful Glare": "Olhar Vingativo",
    "Wall of Ice": "Muralha de Gelo",
    "War Pick": "Picareta de Guerra",
    "Warhammer": "Martelo de Guerra",
    "Water Jet": "Jato d'Água",
    "Whelm": "Engolir",
    "Whip": "Chicote",
    "Whirlwind": "Redemoinho",
    "Withering Touch": "Toque Definhador",
}
